import { defineConfig, defineDocs } from "fumadocs-mdx/config";

// Docs live in ./content/docs as MDX. fumadocs-mdx generates .source/ from them
// (git-ignored, regenerated by the `fumadocs-mdx` postinstall + on `next dev`/`build`).
export const { docs, meta } = defineDocs({
  dir: "content/docs",
});

export default defineConfig();
